config/routes.rb
Rails.application.routes.draw do
  resources :programming_languages
  root to: 'programming_languages#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/programming_language.rb
class ProgrammingLanguage < ActiveRecord::Base
  has_and_belongs_to_many :types
  has_and_belongs_to_many :authors

  searchable do
    text :name
    text :types do
      types.map(&:name)
    end
    text :authors do
      authors.map(&:name)
    end
  end

end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController

  before_action :find_language, only: [:show, :edit, :update, :destroy]

  def index
    paginate_params = { page: params[:page], per_page: 15 }
    @languages = 
    if !params[:search].blank?
      ProgrammingLanguage.search do
        fulltext params[:search]
        paginate paginate_params
      end.results
    else
      ProgrammingLanguage.paginate(paginate_params)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @language = ProgrammingLanguage.new
  end

  def create
    @language = ProgrammingLanguage.new(params[:programming_language])
    if @language.save
      flash[:success] = "New programming language was created successfully"
      redirect_to programming_languages_path
    else
      flash[:error] = "Cannot be saved"
      render "new"
    end
  end

  def edit
  end

  def update
    if @language.update_attributes(programming_language_params)
      flash[:success] = "Programming language was updated successfully"
      redirect_to programming_language_path
    else
      flash[:error] = "Cannot be saved"
      render "edit"
    end
  end

  def destroy
    @language.destroy
    flash[:success] = "#{@language.name} was deleted"
  end

  private

  def find_language
    @language = ProgrammingLanguage.find(params[:id])
  end

  def programming_language_params
    params.require(:programming_language).permit(:name, {type_ids: []}, {author_ids: []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programming_languages_helper.rb
module ProgrammingLanguagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Searchable</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <a class="navbar-brand" href="#">Demo App</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Languages", programming_languages_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
  </nav>
  <div class="container">
    <%= render partial: "shared/flash", flash: flash %>
    <div class="starter-template">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/programming_languages/_form.html.haml
.form-group
  = f.label :name
  = f.text_field :name
.form-group
  = f.label "Type:"
  = f.collection_check_boxes(:type_ids, Type.order(:name), :id, :name) do |b|
    = b.label { b.check_box + b.text }
.form-group
  = f.label "Designed by:"
  = f.collection_check_boxes(:author_ids, Author.order(:name), :id, :name) do |b|
    = b.label { b.check_box + b.text }
= f.submit "Save", {class: "btn btn-default"}

app/views/programming_languages/_languages.html.haml
#languages_list
  %ul.list-unstyled
    - languages.each_with_index do |lang, i|
      %li.lang_info{style: "background-color: #{i%2 == 0 ? '#ECFAFF' : '#DCDCDC'}"}
        %h4= link_to(lang.name, lang)
        %dl.def-list
          %dt= "Type"
          %dd= lang.types.map(&:name).join(", ")
          %dt= "Designed By"
          %dd= lang.authors.map(&:name).join(", ")
  = will_paginate languages

app/views/programming_languages/edit.html.haml
= form_for @language do |f|
  = render partial: "form", locals: {f: f}

app/views/programming_languages/index.html.haml
%h1= "Programming Languages"

= form_tag(programming_languages_path, method: 'get', class: "form-inline", remote: true) do
  = text_field_tag(:search, params[:search], class: 'form-control', placeholder: "Search...")
  = submit_tag("Search", class: "btn btn-primary")

= render partial: "languages", locals: {languages: @languages}

:javascript
  if (#{params[:search].blank? ? false : true}) {
    $('#languages_list ul').highlight_words("#{params[:search]}");
  }

app/views/programming_languages/index.js.haml
- search_result = @languages.empty? ? "No results match '#{params[:search]}'" : render(partial: 'languages', locals: {languages: @languages, search: @search})
$('#languages_list').html("#{escape_javascript(search_result)}");
- unless params[:search].blank?
  $('#languages_list ul').highlight_words("#{params[:search]}");

app/views/programming_languages/new.html.haml
- form_for @language do |f|
  = render partial: "form", locals: {f: f}

app/views/programming_languages/show.html.haml
%h1= @language.name
%dl
  %dt= "Type:"
  %dd= @language.types.map(&:name).join(", ")
  %dt= "Designed by:"
  %dd= @language.authors.map(&:name).join(", ")
.edit_lang= link_to("Edit", edit_programming_language_path(@language))

app/views/shared/_flash.html.haml
- flash.each do |type, msg|
  %div{ class: "alert alert-#{type} alert-dismissable fade in"}
    %button.close{type: "button", "data-dismiss" => "alert"}= "x"
    = msg